{
 "title": "Prometheus Proxy",
 "time": { "from": "2020-04-08T22:28:38.562Z", "to": "2020-04-08T22:31:22.858Z" },
 "panels": [
  {
   "title": "Unrecognized RSockets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_proxy_unrecognized_rsocket_total",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RSocket Request/Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsocket_request_response_seconds_count{signal_type=\"ON_COMPLETE\"}[1m]))",
     "legendFormat": "complete"
    },
    {
     "expr": "sum(rate(rsocket_request_response_seconds_count{signal_type=\"CANCEL\"}[1m]))",
     "legendFormat": "cancel"
    },
    {
     "expr": "sum(rate(rsocket_request_response_seconds_count{signal_type=\"ON_ERROR\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Prometheus Scrapes of Individual Processes by Outcome",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "scrapes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_proxy_scrape_seconds_count{outcome=\"success\"}[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(prometheus_proxy_scrape_seconds_count{outcome=\"closed\"}[1m]))",
     "legendFormat": "closed"
    },
    {
     "expr": "sum(rate(prometheus_proxy_scrape_seconds_count{outcome=\"error\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "prometheus_proxy_scrape_active_connections",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Maximum Scrape Payload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "scrape payload size" }
   ],
   "targets": [
    {
     "expr": "prometheus_proxy_scrape_payload_bytes_max",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(prometheus_proxy_scrape_payload_bytes_count[1m]))",
     "legendFormat": "count"
    }
   ]
  }
 ]
}